// ----------------------- PROFILE -------------------------
// PROFILE DAN PENGGUNA IN HERE 
// CLASS PENGGUNA WILL UPDATE AFTER PROFILE DONE EVERYTHINGS ....
// KEEP WAITING FOR NEXT UPDATE .... SO THIS SCRIPT WILL UPDATE IN EVERY DAY OR WEEKS. TOO MUCH TO CHANGED ABOUT CONTAINER TO DIV SELECTOR!! WE (TEAM TOKKO) ALWAYS GIVING THE FREEDOM TO TAKE ALL SUPPORT AND PROBLEMS ABOUT TOKKO LOGIN SCRIPT
// ----------------------------------------------------
// THIS SCRIPT CREATED BY TOKKO BLOGGER ( HELMY HYKO )
// ----------------------------------------------------








// ----------------------- USERS -------------------------
// PROFILE DAN PENGGUNA IN HERE 
// CLASS PENGGUNA WILL UPDATE AFTER PROFILE DONE EVERYTHINGS ....
// KEEP WAITING FOR NEXT UPDATE .... SO THIS SCRIPT WILL UPDATE IN EVERY DAY OR WEEKS. TOO MUCH TO CHANGED ABOUT CONTAINER TO DIV SELECTOR!! WE (TEAM TOKKO) ALWAYS GIVING THE FREEDOM TO TAKE ALL SUPPORT AND PROBLEMS ABOUT TOKKO LOGIN SCRIPT
// ----------------------------------------------------
// THIS SCRIPT CREATED BY TOKKO BLOGGER ( HELMY HYKO )
// ----------------------------------------------------















// -----------------------GUILD -------------------------
// PROFILE DAN PENGGUNA IN HERE 
// CLASS PENGGUNA WILL UPDATE AFTER PROFILE DONE EVERYTHINGS ....
// KEEP WAITING FOR NEXT UPDATE .... SO THIS SCRIPT WILL UPDATE IN EVERY DAY OR WEEKS. TOO MUCH TO CHANGED ABOUT CONTAINER TO DIV SELECTOR!! WE (TEAM TOKKO) ALWAYS GIVING THE FREEDOM TO TAKE ALL SUPPORT AND PROBLEMS ABOUT TOKKO LOGIN SCRIPT
// ----------------------------------------------------
// THIS SCRIPT CREATED BY TOKKO BLOGGER ( HELMY HYKO )
// ----------------------------------------------------



